apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-svc
  labels:
    app: karsajobs-ui-svc
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: karsajobs-frontend
  type: ClusterIP