apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: mongo-statefulset
spec:
  selector:
    matchLabels:
      app: mongo-statefulset
  serviceName: mongo-svc
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:8
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME"
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: config
          mountPath: /config
        - name: cred
          mountPath: /etc/mongo-credentials
          readOnly: true
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: config
        configMap:
          name: mongo-config
      - name: cred
        secret:
          secretName: mongo-cred